import BernsteinObstacle.PhysicalSimplexCalculus
import BernsteinObstacle.SamplingQuadraticGuard

#print axioms BernsteinObstacle.simplexBasis_eq_simplexBasisNat
#print axioms BernsteinObstacle.simplexBasis_sum_eq_one
#print axioms BernsteinObstacle.simplexField_const
#print axioms BernsteinObstacle.simplexField_lower_bound
#print axioms BernsteinObstacle.simplexField_upper_bound
#print axioms BernsteinObstacle.simplexSamplingRecovery_const
#print axioms BernsteinObstacle.simplexSamplingRecovery_mem_Icc
#print axioms BernsteinObstacle.simplexSamplingRecovery_sub
#print axioms BernsteinObstacle.simplexSamplingRecovery_abs_sub_le
#print axioms BernsteinObstacle.simplexSamplingRecovery_abs_error_le
#print axioms BernsteinObstacle.physicalSimplexPoint_sub
#print axioms BernsteinObstacle.norm_physicalSimplexPoint_sub_le
#print axioms BernsteinObstacle.physicalSimplexPoint_diameter_le
#print axioms BernsteinObstacle.physicalSamplingRecovery_nonneg
#print axioms BernsteinObstacle.physicalSamplingRecovery_const
#print axioms BernsteinObstacle.simplexMultiIndex_sum_eq_piAntidiag
#print axioms BernsteinObstacle.simplexBasis_first_moment
#print axioms BernsteinObstacle.simplexSamplingRecovery_coordinate
#print axioms BernsteinObstacle.simplexSamplingRecovery_affine
#print axioms BernsteinObstacle.physicalSamplingRecovery_affine
#print axioms BernsteinObstacle.physicalSamplingRecovery_taylor_error_le
#print axioms BernsteinObstacle.convex_range_physicalSimplexPoint
#print axioms BernsteinObstacle.norm_taylor_remainder_le_of_lipschitz_fderiv
#print axioms BernsteinObstacle.physicalSamplingRecovery_abs_error_le_of_lipschitz_fderiv
#print axioms BernsteinObstacle.physicalSamplingRecovery_abs_error_le
#print axioms BernsteinObstacle.curve_square_sampling_error
#print axioms BernsteinObstacle.curve_square_sampling_midpoint_error
