import BernsteinObstacle.PhysicalEnergyExistence
import Mathlib.Topology.Order.Compact

open MeasureTheory Set Function Filter Topology
open scoped ENNReal NNReal BigOperators

namespace BernsteinObstacle

noncomputable section

variable {α ι : Type*} [MeasurableSpace α] {μ : Measure α} [Fintype ι]

/-- The literal nonnegative finite coefficient cone in actual L2. -/
def positiveFiniteLpCone (g : ι → Lp ℝ 2 μ) : Set (Lp ℝ 2 μ) :=
  {u | ∃ c : ι → ℝ, (∀ i, 0 ≤ c i) ∧ u = ∑ i, c i • g i}

theorem norm_le_of_nonnegative_Lp_order (f g : Lp ℝ 2 μ)
    (hf : 0 ≤ f) (hg : 0 ≤ g) (hfg : f ≤ g) : ‖f‖ ≤ ‖g‖ := by
  apply Lp.norm_le_norm_of_ae_le
  filter_upwards [(Lp.coeFn_nonneg f).mpr hf, (Lp.coeFn_nonneg g).mpr hg,
    (Lp.coeFn_le f g).mpr hfg] with x hfx hgx hfgx
  simpa only [Real.norm_eq_abs, abs_of_nonneg hfx, abs_of_nonneg hgx] using hfgx

/-- Positivity prevents cancellation, so each nonzero generator controls
its own coefficient. No linear independence or strictly positive basis is
assumed; zero generators are explicitly harmless. -/
theorem positiveFiniteLp_component_bound (g : ι → Lp ℝ 2 μ) (hg : ∀ i, 0 ≤ g i)
    (c : ι → ℝ) (hc : ∀ i, 0 ≤ c i) (i : ι) :
    c i * ‖g i‖ ≤ ‖∑ j, c j • g j‖ := by
  have hterm (j : ι) : 0 ≤ c j • g j := by
    apply (Lp.coeFn_nonneg _).mp
    filter_upwards [Lp.coeFn_smul (c j) (g j), (Lp.coeFn_nonneg (g j)).mpr (hg j)]
      with x hsm hx
    rw [hsm, Pi.smul_apply, smul_eq_mul]
    exact mul_nonneg (hc j) hx
  have hsum : 0 ≤ ∑ j, c j • g j := Finset.sum_nonneg (fun j _ => hterm j)
  have hle : c i • g i ≤ ∑ j, c j • g j :=
    Finset.single_le_sum (fun j _ => hterm j) (Finset.mem_univ i)
  simpa only [norm_smul, Real.norm_eq_abs, abs_of_nonneg (hc i)] using
    norm_le_of_nonnegative_Lp_order (c i • g i) (∑ j, c j • g j) (hterm i) hsum hle

/-- Every finite cone generated by nonnegative actual L2 functions is
closed. Normalize coefficients of zero generators to zero, bound all other
coefficients using their L2 norms, and extract a limit in a compact real
coefficient box. This does not appeal to an assumed polyhedral-cone theorem. -/
theorem isClosed_positiveFiniteLpCone (g : ι → Lp ℝ 2 μ) (hg : ∀ i, 0 ≤ g i) :
    IsClosed (positiveFiniteLpCone g) := by
  classical
  apply IsSeqClosed.isClosed
  intro u z hmem hconv
  change ∀ n, ∃ c : ι → ℝ, (∀ i, 0 ≤ c i) ∧ u n = ∑ i, c i • g i at hmem
  choose c hc heq using hmem
  let a : ℕ → ι → ℝ := fun n i => if g i = 0 then 0 else c n i
  have ha (n : ℕ) (i : ι) : 0 ≤ a n i := by
    dsimp [a]
    split_ifs
    · exact le_refl 0
    · exact hc n i
  have har (n : ℕ) : u n = ∑ i, a n i • g i := by
    rw [heq n]
    apply Finset.sum_congr rfl
    intro i _hi
    dsimp [a]
    split_ifs with hgi
    · simp only [hgi, smul_zero]
    · rfl
  have hab (n : ℕ) (i : ι) : a n i * ‖g i‖ ≤ ‖u n‖ := by
    rw [har n]
    exact positiveFiniteLp_component_bound g hg (a n) (ha n) i
  let upper : ι → ℝ := fun i => (‖z‖ + 1) / ‖g i‖
  have hnorm : ∀ᶠ n in atTop, ‖u n‖ < ‖z‖ + 1 :=
    hconv.norm.eventually (gt_mem_nhds (lt_add_one ‖z‖))
  have hbox : ∀ᶠ n in atTop, a n ∈ Icc (0 : ι → ℝ) upper := by
    filter_upwards [hnorm] with n hn
    refine ⟨ha n, ?_⟩
    intro i
    by_cases hgi : g i = 0
    · simp only [a, hgi, if_pos, upper, norm_zero, div_zero, le_refl]
    · exact (le_div_iff₀ (norm_pos_iff.mpr hgi)).mpr ((hab n i).trans hn.le)
  obtain ⟨a₀, ha₀, φ, hφ, hlim⟩ :=
    (isCompact_Icc (a := (0 : ι → ℝ)) (b := upper)).tendsto_subseq' hbox.frequently
  have hmap : Continuous (fun t : ι → ℝ => ∑ i, t i • g i) :=
    continuous_finsetSum _ (fun i _ => (continuous_apply i).smul continuous_const)
  have hsumlim := hmap.tendsto a₀ |>.comp hlim
  have hsum : (fun n => ∑ i, a (φ n) i • g i) = u ∘ φ :=
    funext (fun n => (har (φ n)).symm)
  change Tendsto (fun n => ∑ i, a (φ n) i • g i) atTop (𝓝 (∑ i, a₀ i • g i)) at hsumlim
  rw [hsum] at hsumlim
  exact ⟨a₀, ha₀.1, tendsto_nhds_unique (hconv.comp hφ.tendsto_atTop) hsumlim⟩

end

end BernsteinObstacle
